# Generated by Django 3.2.12 on 2022-03-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_project', '0006_uploadedfile_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='name',
            field=models.CharField(default='test_model', max_length=50),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='name',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
