# Generated by Django 3.2.12 on 2022-03-30 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_project', '0008_dataset_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='scores',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
