# Generated by Django 3.2.12 on 2022-03-31 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_project', '0009_mlmodel_scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='sklearn_json',
            field=models.FileField(upload_to=''),
        ),
    ]
