# Generated by Django 3.2.12 on 2022-03-31 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_project', '0010_alter_mlmodel_sklearn_json'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mlmodel',
            old_name='sklearn_json',
            new_name='sklearn_pkl',
        ),
    ]
