# Generated by Django 3.2.12 on 2022-03-31 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_project', '0011_rename_sklearn_json_mlmodel_sklearn_pkl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='sklearn_pkl',
            field=models.FileField(upload_to='sklearn_models/'),
        ),
    ]
